config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  resources :fruits, only: %i[create index]

  namespace :fruits do
    resources :nutritional, only: %i[index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits/nutritional_controller.rb
module Fruits
  class NutritionalController < ApplicationController
    # GET /fruits/nutritional
    def index
      @related_fruits = SearchFacade.new.related_by_calories(params[:max_calories])
    end
  end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  def index
    @fruit = SearchFacade.new.fruit_named(params[:query])
  end

  def create
    @fruit = SearchFacade.new.fruit_named(params[:search])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fruits/create.html.erb
<h1>Search Results</h1>
<h2><%= "Name: #{@fruit.name}" %></h2>
<h3><%= "Family: #{@fruit.family}" %></h3>
<h3><%= "Order: #{@fruit.order}" %></h3>
<h3><%= "Genus: #{@fruit.genus}" %></h3>
<h3><%= "Nutrition:" %></h2>
<ul>
  <li><%= "Calories: #{@fruit.calories}" %>
  <li><%= "Fat: #{@fruit.fat}" %>
  <li><%= "Sugar: #{@fruit.sugar}" %>
  <li><%= "Carbohydrates: #{@fruit.carbohydrates}" %>
  <li><%= "Protein: #{@fruit.protein}" %>
</ul>

<h4><%= link_to "Find Similar Fruits by Nutrition Value", fruits_nutritional_index_path(max_calories: @fruit.calories)%>

app/views/fruits/index.html.erb
<h1>Search Results</h1>
<h2><%= "Name: #{@fruit.name}" %></h2>
<h3><%= "Family: #{@fruit.family}" %></h3>
<h3><%= "Order: #{@fruit.order}" %></h3>
<h3><%= "Genus: #{@fruit.genus}" %></h3>
<h3><%= "Nutrition:" %></h2>
<ul>
  <li><%= "Calories: #{@fruit.calories}" %>
  <li><%= "Fat: #{@fruit.fat}" %>
  <li><%= "Sugar: #{@fruit.sugar}" %>
  <li><%= "Carbohydrates: #{@fruit.carbohydrates}" %>
  <li><%= "Protein: #{@fruit.protein}" %>
</ul>

<h4><%= link_to "Find Similar Fruits by Nutrition Value", fruits_nutritional_index_path(max_calories: @fruit.calories)%>

app/views/fruits/nutritional/index.html.erb
<h1>Related Fruits</h1>
<% @related_fruits.each do |fruit| %>
  <div id="related_fruit-<%= fruit.name %>">
    <h2><%= link_to "Name: #{fruit.name}", fruits_path(query: fruit.name)  %></h2>
    <h3><%= "Family: #{fruit.family}" %></h3>
    <h3><%= "Order: #{fruit.order}" %></h3>
    <h3><%= "Genus: #{fruit.genus}" %></h3>
    <h3><%= "Nutrition:" %></h2>
    <ul>
      <li><%= "Calories: #{fruit.calories}" %>
      <li><%= "Fat: #{fruit.fat}" %>
      <li><%= "Sugar: #{fruit.sugar}" %>
      <li><%= "Carbohydrates: #{fruit.carbohydrates}" %>
      <li><%= "Protein: #{fruit.protein}" %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FruitApi7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Fruit Search</h1>
<%= form_with url: "/fruits", method: :post, data: { turbo: false } do |f| %>
   <%= f.label :search, "Search for Fruit" %>
   <%= f.text_field :search %>

   <%= f.submit "Search" %>
<% end %>